"""
Base environment abstraction for agent RL training.

A ToolEnv manages the multi-turn interaction loop:
  1. The model generates text (possibly containing tool calls)
  2. The env parses tool calls, executes them, and returns observations
  3. Repeat until the model emits a final answer or max_turns is reached
  4. The env computes rewards (both per-turn and trajectory-level)

The key design principle is that **the entire trajectory is flattened
into a single token sequence** for training, with segment boundaries
recorded so that TraceRL/random-masking can distinguish model-generated
tokens from environment-injected observations.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple
import json
import re

from agent.base_tool import BaseTool, ToolResult


# ── Special tokens used in the multi-turn agent protocol ──────────────────
# These are template-level strings; the actual special tokens depend on the
# tokenizer.  We use a generic format that works with most chat templates.
TOOL_CALL_START = "<|tool_call_start|>"
TOOL_CALL_END = "<|tool_call_end|>"
OBSERVATION_START = "<|observation_start|>"
OBSERVATION_END = "<|observation_end|>"
FINAL_ANSWER_START = "<|final_answer_start|>"
FINAL_ANSWER_END = "<|final_answer_end|>"


@dataclass
class Turn:
    """A single turn in the agent trajectory."""

    role: str  # "assistant", "tool", "observation"
    content: str
    # For assistant turns: which tokens were generated by the model
    # For observation turns: these are env-injected (not trained on)
    is_model_generated: bool = True
    tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    tool_results: List[ToolResult] = field(default_factory=list)
    turn_reward: float = 0.0  # per-turn reward (optional)


@dataclass
class Trajectory:
    """
    A complete agent trajectory (multi-turn interaction).

    This is the fundamental data structure for agent RL. It records:
    - The initial prompt (user question)
    - All turns (assistant generations + tool observations)
    - Segment boundaries for knowing which tokens to train on
    - Per-turn and trajectory-level rewards
    """

    prompt: str
    turns: List[Turn] = field(default_factory=list)
    final_answer: str = ""
    # The full flattened text (prompt + all turns concatenated)
    full_text: str = ""
    # Segment boundaries: list of (start_idx, end_idx, is_trainable)
    # is_trainable=True for model-generated segments, False for observations
    segments: List[Tuple[int, int, bool]] = field(default_factory=list)
    # The diffusion step_map for the entire trajectory
    step_maps: List[List[int]] = field(default_factory=list)
    # Rewards
    turn_rewards: List[float] = field(default_factory=list)
    trajectory_reward: float = 0.0
    # Metadata
    ground_truth: str = ""
    task_data: Dict[str, Any] = field(default_factory=dict)


class BaseToolEnv(ABC):
    """
    Abstract base class for tool environments.

    A tool environment defines:
    1. What tools are available
    2. How to parse tool calls from model output
    3. How to format observations back into the conversation
    4. How to compute rewards (per-turn and trajectory-level)
    5. When to stop the interaction (max turns, final answer detected, etc.)

    The environment operates at the STRING level (not token level) during
    rollout. Token-level processing happens in the training script.
    """

    def __init__(
        self,
        tools: List[BaseTool],
        max_turns: int = 5,
        max_tokens_per_turn: int = 512,
        tool_call_format: str = "json",  # "json" or "xml"
    ):
        self.tools = {tool.name: tool for tool in tools}
        self.max_turns = max_turns
        self.max_tokens_per_turn = max_tokens_per_turn
        self.tool_call_format = tool_call_format

    def get_tool_descriptions(self) -> str:
        """
        Generate the tool description string for the system prompt.
        This tells the model what tools are available and how to call them.
        """
        tool_descs = []
        for tool in self.tools.values():
            schema = tool.get_schema()
            params_str = json.dumps(schema["parameters"], indent=2)
            tool_descs.append(
                f"### {schema['name']}\n"
                f"{schema['description']}\n"
                f"Parameters:\n```json\n{params_str}\n```"
            )

        format_instruction = self._get_format_instruction()
        return (
            "You have access to the following tools:\n\n"
            + "\n\n".join(tool_descs)
            + "\n\n"
            + format_instruction
        )

    def _get_format_instruction(self) -> str:
        """Instruction for how the model should format tool calls."""
        return (
            "To use a tool, output a tool call in the following format:\n"
            f"{TOOL_CALL_START}\n"
            '{"name": "<tool_name>", "arguments": {<args>}}\n'
            f"{TOOL_CALL_END}\n\n"
            "After receiving the observation, you can continue reasoning or "
            "provide your final answer.\n"
            f"When you have the final answer, wrap it in:\n"
            f"{FINAL_ANSWER_START}<your answer>{FINAL_ANSWER_END}"
        )

    def parse_tool_calls(self, text: str) -> List[Dict[str, Any]]:
        """
        Parse tool calls from the model's generated text.

        Returns a list of dicts with 'name' and 'arguments' keys.
        """
        tool_calls = []
        pattern = re.escape(TOOL_CALL_START) + r"(.*?)" + re.escape(TOOL_CALL_END)
        matches = re.findall(pattern, text, re.DOTALL)

        for match in matches:
            try:
                call = json.loads(match.strip())
                if "name" in call:
                    tool_calls.append(call)
            except json.JSONDecodeError:
                # Try to extract name and arguments even from malformed JSON
                name_match = re.search(r'"name"\s*:\s*"([^"]+)"', match)
                if name_match:
                    tool_calls.append(
                        {
                            "name": name_match.group(1),
                            "arguments": {},
                            "_parse_error": True,
                        }
                    )
        return tool_calls

    def parse_final_answer(self, text: str) -> Optional[str]:
        """Extract the final answer from model output, if present."""
        pattern = re.escape(FINAL_ANSWER_START) + r"(.*?)" + re.escape(FINAL_ANSWER_END)
        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1).strip()
        return None

    def execute_tool_calls(self, tool_calls: List[Dict[str, Any]]) -> List[ToolResult]:
        """Execute a list of parsed tool calls and return results."""
        results = []
        for call in tool_calls:
            tool_name = call.get("name", "")
            arguments = call.get("arguments", {})

            if tool_name not in self.tools:
                results.append(
                    ToolResult(
                        tool_name=tool_name,
                        success=False,
                        output=f"Error: Tool '{tool_name}' not found. Available tools: {list(self.tools.keys())}",
                    )
                )
                continue

            try:
                result = self.tools[tool_name].execute(**arguments)
                results.append(result)
            except Exception as e:
                results.append(
                    ToolResult(
                        tool_name=tool_name,
                        success=False,
                        output=f"Error executing tool '{tool_name}': {str(e)}",
                    )
                )
        return results

    def format_observation(self, results: List[ToolResult]) -> str:
        """
        Format tool results into an observation string to inject
        back into the conversation.
        """
        obs_parts = []
        for result in results:
            status = "Success" if result.success else "Error"
            obs_parts.append(f"[{result.tool_name}] ({status})\n{result.output}")
        observation = "\n".join(obs_parts)
        return f"{OBSERVATION_START}\n{observation}\n{OBSERVATION_END}"

    def should_stop(self, text: str, turn_idx: int) -> bool:
        """
        Check if the interaction should stop.
        Returns True if:
        - A final answer was detected
        - Max turns reached
        - No tool calls and no final answer (model just gave a response)
        """
        if self.parse_final_answer(text) is not None:
            return True
        if turn_idx >= self.max_turns:
            return True
        tool_calls = self.parse_tool_calls(text)
        if not tool_calls:
            # No tool call and no final answer - treat as implicit final answer
            return True
        return False

    @abstractmethod
    def compute_reward(self, trajectory: Trajectory) -> Trajectory:
        """
        Compute rewards for a completed trajectory.

        Must set:
        - trajectory.trajectory_reward (float): overall trajectory reward
        - trajectory.turn_rewards (list of float): per-turn rewards

        Returns the trajectory with rewards filled in.
        """
        raise NotImplementedError

    def get_system_prompt(self, task_data: Dict[str, Any]) -> str:
        """
        Build the full system prompt for a given task.
        Includes tool descriptions and task-specific instructions.

        Override this to customize the prompt format for your task.
        """
        tool_desc = self.get_tool_descriptions()
        return tool_desc

    def reset(self):
        """Reset all tools and env state between episodes."""
        for tool in self.tools.values():
            tool.reset()
